# Numpy basic method

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a


array([1, 2, 3])

In [4]:
print(a
     )

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [7]:
b = np.array([[1,2,3],[4,5,6]])

In [8]:
b


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
c1 = np.array([0,1,2,3,4,5])

In [11]:
c1

array([0, 1, 2, 3, 4, 5])

In [12]:
c2 = c1.reshape((2,3))

In [13]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c3 = c2.ravel()

In [15]:
c3

array([0, 1, 2, 3, 4, 5])

In [16]:
c4 = c2.flatten()

In [17]:
c4

array([0, 1, 2, 3, 4, 5])

In [18]:
a.dtype

dtype('int64')

In [20]:
d = np.array([1,2],dtype=np.int16)

In [21]:
d.dtype

dtype('int16')

In [23]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [24]:
a

array([1, 2, 3])

In [25]:
a[0]

1

In [26]:
a[1:]

array([2, 3])

In [27]:
a[-1]

3

In [28]:
a[::-1]

array([3, 2, 1])

In [33]:
a[2:0]

array([], dtype=int64)

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b[1]

array([4, 5, 6])

In [36]:
b[:,2]

array([3, 6])

In [37]:
b[1,:]

array([4, 5, 6])

In [38]:
b[0,1:]

array([2, 3])

In [39]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [40]:
b[1,2]=7

In [41]:
b

array([[1, 2, 3],
       [4, 5, 7]])

In [42]:
b[:,2]=8

In [43]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [44]:
a1= q

NameError: name 'q' is not defined

In [45]:
a1=a

In [46]:
a1[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [47]:
a1[1]=5

In [48]:
a1

array([1, 5, 3])

In [49]:
a

array([1, 5, 3])

In [50]:
a2=a.copy()

In [51]:
a2

array([1, 5, 3])

In [52]:
a2[0]=6
a2

array([6, 5, 3])

In [53]:
a

array([1, 5, 3])

In [54]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0]=6
c4[1]=7

In [57]:
c3

array([6, 1, 2, 3, 4, 5])

In [58]:
c4

array([0, 7, 2, 3, 4, 5])

In [59]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [60]:
pylist1=[0,1]
pylist2=pylist1[:]
pylist2[0]=2
print(pylist1)
print(pylist2)

[0, 1]
[2, 1]


In [63]:
nparray1=np.array([0,1])
nparray2=nparray1[:]
nparray2[0]=2
print(nparray1)
print(nparray2)

[2 1]
[2 1]


In [65]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
np.arange(4,90,5)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89])

In [71]:
f=np.random.random((4,2))

In [69]:
f

array([[0.38656317, 0.39720966],
       [0.77723957, 0.14380034],
       [0.42264464, 0.00678511],
       [0.57185779, 0.76289804]])

In [70]:
f

array([[0.38656317, 0.39720966],
       [0.77723957, 0.14380034],
       [0.42264464, 0.00678511],
       [0.57185779, 0.76289804]])

In [72]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [73]:
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [74]:
np.random.seed(123)
np.random.randint(1,10)

3

In [76]:
np.random.seed(123)
np.random.randint(1,10,(3,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [77]:
np.random.seed(123)
np.random.uniform(size=(4,3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [78]:
np.random.uniform(1,3,size=(4,3))

array([[1.87714449, 1.11935579, 1.79608851],
       [2.47599081, 1.36498346, 1.35090351],
       [2.06310275, 2.06365517, 2.26880192],
       [2.69886359, 2.44891065, 2.22204702]])

In [79]:
np.random.randn(4,4)

array([[-0.93583387,  1.17582904, -1.25388067, -0.6377515 ],
       [ 0.9071052 , -1.4286807 , -0.14006872, -0.8617549 ],
       [-0.25561937, -2.79858911, -1.7715331 , -0.69987723],
       [ 0.92746243, -0.17363568,  0.00284592,  0.68822271]])

In [81]:
np.random.normal(0,1,size=(5,5))

array([[-2.02504576, -0.27578601, -0.55210807,  0.12074736,  0.74821562],
       [ 1.60869097, -0.27023239,  0.81234133,  0.49974014,  0.4743473 ],
       [-0.56392393, -0.99732147, -1.10004311, -0.75643721,  0.32168658],
       [ 0.76094939,  0.32346885, -0.5489551 ,  1.80597011,  1.51886562],
       [-0.35400011, -0.82343141,  0.13021495,  1.26729865,  0.33276498]])

In [82]:
np.zeros(3)

array([0., 0., 0.])

In [83]:
np.zeros(3,3)

TypeError: data type not understood

In [84]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [86]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [87]:
np.full((2,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [88]:
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [89]:
l=np.array([2,5,-8,9,35])
np.diff(l)

array([  3, -13,  17,  26])

In [90]:
print(a)
print(a1)

[1 5 3]
[1 5 3]


In [91]:
np.concatenate([a,a1])

array([1, 5, 3, 1, 5, 3])

In [92]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [93]:
b1=np.array([[10],[20]])

In [94]:
b1

array([[10],
       [20]])

In [95]:
np.concatenate([b,b1],axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [96]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [97]:
b2=np.array([30,60,45])

In [98]:
b3=np.vstack([b,b2])

In [99]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [100]:
first,second=np.hsplit(b3,[2])
first
second

array([[ 8],
       [ 8],
       [45]])

In [101]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [102]:
first1,second1=np.vsplit(b3,[2])

In [103]:
print(first1)
print(second1)

[[1 2 8]
 [4 5 8]]
[[30 60 45]]


In [104]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [105]:
b3.T

array([[ 1,  4, 30],
       [ 2,  5, 60],
       [ 8,  8, 45]])

In [106]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [107]:
a

array([1, 5, 3])

In [108]:
a[np.newaxis,:]

array([[1, 5, 3]])

In [109]:
m=np.arange(0,4)

In [110]:
n=np.arange(4,7)

In [111]:
xx,yy=np.meshgrid(m,n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [112]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [113]:
m

array([0, 1, 2, 3])

In [114]:
n

array([4, 5, 6])