# Data preprocessing

# fill N/A

In [1]:
import numpy as np
import pandas as pd

#sample dataset
df = pd.DataFrame(
        {
            'A':[1,np.nan,3,4,5],
            'B':[6,7,8,np.nan,10],
            'C':[11,12,13,14,15]
        })
df

A     B   C
0  1.0   6.0  11
1  NaN   7.0  12
2  3.0   8.0  13
3  4.0   NaN  14
4  5.0  10.0  15

In [2]:
df.isnull()

A      B      C
0  False  False  False
1   True  False  False
2  False  False  False
3  False   True  False
4  False  False  False

In [8]:
#欠損の補完
import sklearn as skl
from sklearn.preprocessing import Imputer
#補完用のインスタンスimp作成
imp = Imputer(strategy='mean',axis=0)

#欠損を実際に補完
imp.fit(df)
imp.transform(df)

#アウトプットはndarrayになる

array([[ 1.  ,  6.  , 11.  ],
       [ 3.25,  7.  , 12.  ],
       [ 3.  ,  8.  , 13.  ],
       [ 4.  ,  7.75, 14.  ],
       [ 5.  , 10.  , 15.  ]])

# Encode of Category variables

In [10]:
df = pd.DataFrame(
    {
        'A':[1,2,3,4,5],
        'B':['a','b','b','a','c']
    })
df

A  B
0  1  a
1  2  b
2  3  b
3  4  a
4  5  c

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(df['B'])
le.transform(df['B'])

array([0, 1, 1, 0, 2])

In [12]:
le.classes_

array(['a', 'b', 'c'], dtype=object)

# Feature scaling

In [14]:
#test df
df = pd.DataFrame(
    {
        'A':[1,2,3,4,5],
        'B':[100,200,400,500,800]
    }
)
df

A    B
0  1  100
1  2  200
2  3  400
3  4  500
4  5  800

In [15]:
#分散正規化
#平均０、標準偏差１になるように特徴量を変換

from sklearn.preprocessing import StandardScaler
#make instance
stdsc = StandardScaler()
stdsc.fit(df)
stdsc.transform(df)

array([[-1.41421356, -1.22474487],
       [-0.70710678, -0.81649658],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.40824829],
       [ 1.41421356,  1.63299316]])

In [16]:
#最大最小正規化
#特徴量の最小値が０、最大値が１を取るように変換

from sklearn.preprocessing import MinMaxScaler
#make instance
mmsc = MinMaxScaler()
mmsc.fit(df)
mmsc.transform(df)

array([[0.        , 0.        ],
       [0.25      , 0.14285714],
       [0.5       , 0.42857143],
       [0.75      , 0.57142857],
       [1.        , 1.        ]])

# Classification